using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
// agregar:
using System.IO;
using System.Xml;
using System.Collections.Generic;


namespace XML
{
    public partial class WebForm1 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void cmdCreateXml_Click(object sender, EventArgs e)
        {
            FileStream fs = new FileStream(@"c:\Users\usuario123\proyects\DesApps\Práctica\Fase2\Practica9\SuperProProductList.xml", FileMode.Create);
            XmlTextWriter w = new XmlTextWriter(fs, null);

            w.WriteStartDocument(); // escribe una declaración XML
            w.WriteStartElement("SuperproductoList"); // crea etiquta de apertura de SuperproductoList
            w.WriteComment("Thi file generated by the XmlTextWriter class."); // escribe un comentario

            // escribe el primer producto
            w.WriteStartElement("Product");
            w.WriteAttributeString("ID", "", "1"); // atributo de Product
            w.WriteAttributeString("Name", "", "Chair");

            w.WriteStartElement("Price"); // elemento hijo de Product
            w.WriteString("49.33"); // contenido de Price
            w.WriteEndElement(); // cierra el elemento Price

            w.WriteEndElement(); // cierra el elemento Product

            // escribe el segundo producto
            w.WriteStartElement("Product");
            w.WriteAttributeString("ID", "", "2");
            w.WriteAttributeString("Name", "", "Car");

            w.WriteStartElement("Price");
            w.WriteString("43399.55");
            w.WriteEndElement();

            w.WriteEndElement();

            // escribe el tercer producto
            w.WriteStartElement("Product");
            w.WriteAttributeString("ID", "", "3");
            w.WriteAttributeString("Name", "", "Fresh Fruit Basket");

            w.WriteStartElement("Price");
            w.WriteString("49.99");
            w.WriteEndElement();

            w.WriteEndElement();

            // Cerramos el elemento raiz
            w.WriteEndElement();
            w.WriteEndDocument();
            w.Close();
            lblXml.Text = @"File c:\Users\usuario123\proyects\DesApps\Práctica\Fase2\Practica9\SuperProProductList.xml written successfully.";
        }

        protected void cmdReadXml_Click(object sender, EventArgs e)
        {
            FileStream fs = new FileStream(@"c:\Users\usuario123\proyects\DesApps\Práctica\Fase2\Practica9\SuperProProductList.xml", FileMode.Open);
            XmlTextReader r = new XmlTextReader(fs);

            // Almacenar el archivo en un StringWriter
            // (mucho más rápido que usar operaciones string)
            StringWriter writer = new StringWriter();

            // analiza cada archivo y lee cada nodo
            while (r.Read())
            {
                writer.Write("<b>Type:<b> ");
                writer.Write(r.NodeType.ToString());
                writer.Write("<br>");

                if (r.Name != "")
                {
                    writer.Write("<b>Type:<b> ");
                    writer.Write(r.Name);
                    writer.Write("<br>");
                }

                if (r.Value != "")
                {
                    writer.Write("<b>Value:<b> ");
                    writer.Write(r.Value);
                    writer.Write("<br>");
                }

                if (r.AttributeCount > 0)
                {
                    writer.Write("<b>Attributes:</b> ");
                    for (int i = 0; i < r.AttributeCount; i++)
                    {
                        writer.Write(" ");
                        writer.Write(r.GetAttribute(i));
                        writer.Write(" ");
                    }
                    writer.Write("<br>");
                }
                writer.Write("<br>");
            }
            r.Close();

            // Copy the string content into a label to display it.
            lblXml.Text = writer.ToString();
        }

        protected void cmdReadXmlAsObjects_Click(object sender, EventArgs e)
        {
            FileStream fs = new FileStream(@"c:\Users\usuario123\proyects\DesApps\Práctica\Fase2\Practica9\SuperProProductList.xml", FileMode.Open);
            XmlTextReader r = new XmlTextReader(fs);

            // Creamos una colecion generica de productos.
            List<Product> products = new List<Product>();

            // Iteramos entre los elementos de products.
            while (r.Read())
            {
                if (r.NodeType == XmlNodeType.Element && r.Name == "Product")
                {
                    Product newProduct = new Product();
                    newProduct.ID = Int32.Parse(r.GetAttribute(0));
                    newProduct.Name = r.GetAttribute(1);

                    // Obtenemos el resto de subetiquetas para este producto
                    while (r.NodeType != XmlNodeType.EndElement)
                    {
                        r.Read();
                        // precio

                        if (r.Name == "Price")
                        {
                            while (r.NodeType != XmlNodeType.EndElement)
                            {
                                r.Read();

                                if(r.NodeType == XmlNodeType.Text)
                                {
                                    newProduct.Price = Decimal.Parse(r.Value);
                                }
                            }
                        }
                    }
                    // agregamos el producto a la lista
                    products.Add(newProduct);
                }
            }
            r.Close();

            gridResults.DataSource = products;
            gridResults.DataBind();

        }
    }

}